elasticsearch:
  address: DouyinDBA.raqtpie.xyz
  port: 9200
  user: elastic
  password: elasticnode1

gRPC:
  address: 192.168.1.12
  port: 9421

nacos:
  address: 127.0.0.1
  port: 8848
  server-name: chat-center