gin:
  port: 9421

elasticsearch:
  address: DouyinDBA.raqtpie.xyz
  port: 9200
  user: elastic
  password:

redis:
  address: r-bp12xmzrbjr36iq7lepd.redis.rds.aliyuncs.com
  port: 6379
  password:
  db: 0

nacos:
  address:
  port: 8848
  group: Douyin_GROUP
  server-name: chat-center
  ip: 127.0.0.1