mysql:
  DB: mysql
  DbHost: DouyinDBA.raqtpie.xyz
  DbPort: 3306
  DbUser: DouyinDBA
  DbPassword:
  DbName: DouyinDB

redis:
  RedisDb: redis
  RedisAddr: r-bp12xmzrbjr36iq7lepd.redis.rds.aliyuncs.com:6379
  RedisPw:
  RedisDbName: 2

nacos:
  Ip: 127.0.0.1
  Port: 8848

application:
  ServiceName: user-center
  Ip: localhost
  Port: 8811

  video-center:
    ServiceName: video-center