server:
  address: http://localhost:3000

mysql:
  DB: mysql
  DbHost: DouyinDBA.raqtpie.xyz
  DbPort: 3306
  DbUser: DouyinDBA
  DbPassword:
  DbName: DouyinDB

redis:
  RedisDb: redis
  RedisAddr: r-bp12xmzrbjr36iq7lepd.redis.rds.aliyuncs.com:6379



  RedisPw:
  RedisDbName: 2